server:
  port: 8086

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  # 精确限定扫描路径（去掉classpath*:）
  mapper-locations: classpath:mapper/*.xml
  # 必须添加实体类包扫描,为实体类设置别名
  type-aliases-package: com.schoolwork.epsys.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/users?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  data:
    redis:
      host: localhost  # 新版本的配置位置
      port: 6379
      database: 0
      timeout: 1800000
      password:
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8